- become: true
  gather_facts: true
  hosts: all
  name: Verify
  tasks:
  - ansible.builtin.command:
      cmd: vault operator init
    environment:
      VAULT_SKIP_VERIFY: 'True'
    name: Initialize Vault
  - ansible.builtin.command:
      cmd: vault status
    environment:
      VAULT_ADDR: unix:///run/vault/vault.sock
    failed_when:
    - vault_socket.stdout is not search("Initialized        true")
    name: Use socket to check status
    register: vault_socket
